version: '2'
services:
  node:
    image: nestjs
    container_name: "nestjs"
    build: ./
    working_dir: /nest
    volumes:
      - .:/nest
    ports:
      - 5000:5000
    tty: true
    command: npm start

  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: --serviceExecutor adaptive
